# This workflow integrates ShiftLeft NG SAST with GitHub

name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
 # schedule:
    # * is a special character in YAML so you have to quote this string
 #   - cron:  '3 * * * *'

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app shiftleft-python-example --tag branch=${{ github.head_ref }} --python .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  Build-Rules: 
    runs-on: windows-latest
    needs: NextGen-Static-Analysis
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .
    - name: Validate Build Rules
      run: |
        .\sl check-analysis --app shiftleft-python-example `
        --branch "${{ github.head_ref || steps.extract_branch.outputs.branch }}" `
        --report `
        --github-pr-number=${{github.event.number}} `
        --github-pr-user=${{ github.repository_owner }} `
        --github-pr-repo=${{ github.event.repository.name }} `
        --github-token=${{ secrets.GITHUB_TOKEN }}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
